### ISSUE TITLE
有利用 Readme 做筆記，很棒！

### ISSUE THREAD

**Issue by azole** [angela1393aa/node-workshop#1]
有利用 readme 做筆記，很棒，完全善用了 readme 跟 git 的功能！

這邊小小提醒一下， sum 這邊函式，我看起來會是這樣：

![image](https://user-images.githubusercontent.com/2560515/127745473-f92a0890-f11f-44b5-b543-762d2dd43f11.png)

程式碼是正確的，這邊如果可以注意排版的話就會更棒喔！

**Comment by angela1393aa** [comment]
謝謝老師的提醒，以後會多注意的!!

azole ***@***.***> 於 2021年7月31日 週六 下午11:56寫道：

**Comment by SaladHsieh** [comment]
看pull requests的時候注意到issue，就點進來看，筆記做得好詳細，還補充了一些圖解，覺得好棒，值得學習！謝謝分享！
